# @file sample_config.yaml
# @brief Sample configuration file demonstrating the format for transforms and boundaries.
#
# @author Ruslan Mukhametsafin
# @date   2025-04-10

transforms:
  - parent_frame: "map"
    child_frame: "odom"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 } # Нулевой поворот

  - parent_frame: "odom"
    child_frame: "base_link"
    translation: { x: 1.0, y: 0.5, z: 0.1 } # Смещение робота в одометрии
    rotation: { x: 0.0, y: 0.0, z: 0.707, w: 0.707 } # Поворот на 90 градусов вокруг Z

boundaries:
  map: # Границы для карты
    min: { x: -50.0, y: -50.0, z: -1.0 }
    max: { x: 50.0, y: 50.0, z: 5.0 }

  robot_workspace: # Гипотетический кадр рабочего пространства
     min: { x: -1.0, y: -1.0, z: 0.0 }
     max: { x: 1.0, y: 1.0, z: 1.5 }
